# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [2]:
#code here
import numpy as np

#1D array
arr1= np.arange(12)
print("1D array is:  ",arr1)
#2D array(reshape)
arr2= arr1.reshape(3,4)
print("Reshaped array is: ",arr2)

arr_A=np.array([1,2,3,4,5])
arr_B=np.array([6,7,8,9,10])
print("The first array is: ",arr_A)
print("The second array is: ",arr_B)


#concatenate horizontally
horizontal=np.hstack((arr_A,arr_B))
print("Horizontal concatenation of two arrays is:  ",horizontal)

#concatente vertically
vertical=np.vstack((arr_A,arr_B))
print("Vertical concatenation of two arrays is: ",vertical)

1D array is:   [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array is:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The first array is:  [1 2 3 4 5]
The second array is:  [ 6  7  8  9 10]
Horizontal concatenation of two arrays is:   [ 1  2  3  4  5  6  7  8  9 10]
Vertical concatenation of two arrays is:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [3]:
#code here
def classify_emails(emails):
    important_emails = []
    promotions_emails = []
    spam_emails = []
    
    important_keywords = ['important','urgent']
    promotions_keywords = ['sale','discount']
    spam_keywords = ['lottery', 'Earn $$$']

    for email in emails:
        lower_email = email.lower()
        if any(keyword in lower_email for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in lower_email for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in lower_email for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

demo_emails = [
    "Needs Attention\n"
    "Important Announcements\n"
    "Summer Sale Live now\n"
    "Winter Discounts!!\n"
]

# Calling the function
important, promotions, spam = classify_emails(demo_emails)

# Print the categorized emails
print("Important Emails:")
for email in important:
    print(email)
print("Promotions Emails:")
for email in promotions:
    print(email)
print("Spam Emails:")
for email in spam:
    print(email)

Important Emails:
Needs Attention
Important Announcements
Summer Sale Live now
Winter Discounts!!

Promotions Emails:
Spam Emails:


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [5]:
#code here
english_spanish_dict = {
    "hello": "hola",
    "goodbye": "adios",
    "one": "uno",
    "two": "dos",
    "thank you": "gracias",
}

#the loop keeps on iterating
while True:
    word = input("Enter a word in English: ").lower()

    if word == "exit":
        print("Goodbye!")
        break

    # if the word exists in the dictionary
    if word in english_spanish_dict:
        translation = english_spanish_dict[word]
        print(f"The Spanish translation of '{word}' is '{translation}'.")
    else:
        print("Translation not available.")


Enter a word in English: Hello
The Spanish translation of 'hello' is 'hola'.
Enter a word in English: Two
The Spanish translation of 'two' is 'dos'.
Enter a word in English: Three
Translation not available.
Enter a word in English: Exit
Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [3]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [2]:
# pip install networkx


In [1]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))


In [1]:
import pandas as pd

#acess dataset
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)

#total global sales
total_global_sales = df['Global_Sales'].sum()
print("Total global sales: ", total_global_sales)

#game with the highest global sales
game_with_highest_sales = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:")
print(game_with_highest_sales[['Name', 'Global_Sales']])

#average sales for each region
average_sales_per_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average sales for each region:")
print(average_sales_per_region)

#top 5 most popular game genres based on global sales
top_genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 most popular game genres based on global sales:")
print(top_genres)

#total sales for each genre in each region and the most popular genre in North America
genre_sales_per_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na = genre_sales_per_region['NA_Sales'].idxmax()
print("Most popular genre in North America: ", most_popular_genre_na)

#last 10 rows
print("Last 10 rows of the dataset: ")
print(df.tail(10))

#top 3 gaming platforms with the highest global sales
top_platforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 gaming platforms with the highest global sales:")
print(top_platforms)

#the market share (percentage of global sales) for each genre
genre_market_share = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("Market share for each genre:")
print(genre_market_share)

#the correlation coefficient between NA_Sales and EU_Sales
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation coefficient between NA_Sales and EU_Sales: ", correlation_coefficient)

Total global sales:  8920.44
Game with the highest global sales:
Name            Wii Sports
Global_Sales         82.74
Name: 0, dtype: object
Average sales for each region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 most popular game genres based on global sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
Most popular genre in North America: Action
Last 10 rows of the dataset: 
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                   